### PR TITLE
Compatible with Android Studio 4.0

### PR DESCRIPTION
**Pull request by Omico**
GradleBuildFile has been removed in https://android.googlesource.com/platform/tools/adt/idea/+/f1ab6600402d35687c77afb14397cc76b7e02445.

### CODE REVIEW

**Comment by jeppeman** [comment]
👍 Could you push an empty commit? Forked PR:s were not enabled on Circle CI

**Comment by jeppeman** [comment]
I'll get around to fixing the CI later during the day, will ping you later

**Comment by Omico** [comment]
Ok, see you soon.

**Comment by jeppeman** [comment]
You can rebase on master and push again now

**Comment by Omico** [comment]
You can merge now.

**Pull request merged**
